### distance
POST http://localhost:3002/api/location/districts
content-type: application/json

{

}

### distance/localities-nearest-faps
GET http://localhost:3002/api/distance/localities-nearest-faps
content-type: application/json

{
  "district_id": 2
}

### points/solutions-localities
GET http://localhost:3002/api/points/solutions-localities?population_population_adult_order=ASC&district_id=1
content-type: application/json

### points/conditions-localities
GET http://localhost:3002/api/points/conditions-localities
content-type: application/json

### points/conditions-localities
POST http://localhost:3002/api/points/conditions-localities
content-type: application/json

{
  "min_dist_mc": 6,
  "population_FAP": 1000,
  "population_Ambulatory": 2000
}