# REST Client plugin vs code

# Region--------------------------------------------------------
###

POST http://localhost:3000/api/location/localities

###

POST http://localhost:3000/api/location/regions

# points
###
POST http://localhost:3000/api/points
content-type: application/json

{
    "district_id":3,
    "pointsAdult":20,
    "pointsChild":30,
    "pointsSMP":20,
    "SMPKm":20,

    "pointsStaffing":20,
    "staffingPersent":20,
    
    "pointsState":20,

    "pointsPMSP":20,
    "PMSPKm":20,

    "pointsAge":20,
    "ageYears":1900,

    "deteroationGood":20,
    "deteroationMedium":20,
    "deteroationBad":20,
    "deteroationOld":20,
    "pointsUnfit":20
}

# points/locality
###
POST http://localhost:3000/api/points/localities
content-type: application/json

{
 "district_id":2
}


### clusterize/district

POST http://localhost:3000/api/clusterize/district
content-type: application/json

{
  "district_id":8
}
