### points-mcs
POST http://localhost:3002/api/points/points-mcs
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzEyOTczODYxLCJleHAiOjE3MTMwNjAyNjF9.C1WPw1zlHU15u9OWtzfYy2PxrtP0OiUtjP6MHrKURko

{
  "adult_population": 10,
  "child_population": 2,
  "max_found_year": 4,
  "foundation_year": 4,
  "staffing" : 3,
  "state": 2,
  "each_pers_staffing":2
}

### points-mcs
GET http://localhost:3002/api/points/points-mcs
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzEyOTczODYxLCJleHAiOjE3MTMwNjAyNjF9.C1WPw1zlHU15u9OWtzfYy2PxrtP0OiUtjP6MHrKURko
content-type: application/json

### sulutions-mcs
GET http://localhost:3002/api/points/solutions-mcs?region_id=1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzEyOTczODYxLCJleHAiOjE3MTMwNjAyNjF9.C1WPw1zlHU15u9OWtzfYy2PxrtP0OiUtjP6MHrKURko
content-type: application/json

### medical-centers
GET http://localhost:3002/api/medical-centers?district_id=2
content-type: application/json


